In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.21.6)

In [ ]:
import numpy as np

Q4.3 Using NumPy, provide an expression that sets A to be a 23 NumPy
array, containing any values you wish.

In [ ]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]

Q4.4 Using NumPy, provide an expression that takes a list L of numbers
and returns a 2D NumPy array representing a row vector with those numbers.

In [ ]:
List=[1,2,3,4,5,6]
B=np.array([List])
print(B)

[[1 2 3 4 5 6]]

Q4.5 Using NumPy, provide an expression that takes a list L of numbers
and returns a 2D NumPy array representing a column vector containing those
numbers. You can use the previous expression, if it helps.

In [ ]:
C=B.T
print(C)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Q4.6 Using NumPy, provide an expression that returns the Euclidean norm
of a column vector. The Euclidean norm of a column vector is mathematically
dened as ..., where the ck's are the entries of the vector. Do not forget
you are not allowed to use loops!

In [ ]:
import math
Euclidean=math.sqrt(np.sum(np.power(C,2)))
print(Euclidean)

9.539392014169456

Q4.7 Let X be a 4x2 NumPy array, Y be a 4x3 NumPy array, and Z be
a 4x1 NumPy array. For each of the following expressions, indicate the shape
of the result or if the expression is illegal.(Be aware of what the operators
actually do in Python/NumPy):

In [ ]:
X=np.array([[1,2],[3,4],[5,6],[7,8]])
Y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
Z=np.array([[1],[2],[3],[4]])

a. Z*Z

In [ ]:
A=Z*Z
print(np.shape(A))
#Result:[[1],[4],[9],[16]] ; the shape will be of 4 lines and a column

(4, 1)

b. np.dot(Z,Z)

In [ ]:
print(Z.shape)
B=np.dot(Z,Z)
#the operation will provoke the error: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)
#the operation is illegal because the shapes of the arrays don't correspond for the dot product operation

(4, 1)

ValueError: ignored

In [ ]:
C=np.dot(np.transpose(Z), Z)
print(C.shape)
#result: [[30]] ; the shape will be of a line and a column

(1, 1)

d. np.dot(X, Y )

In [ ]:
print("X =",X.shape)
print("Y =",Y.shape)
D=np.dot(X, Y)
#the operation will provoke the error: shapes (4,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)
#the operation is illegal because the shapes of the arrays don't correspond for the dot product operation

X = (4, 2)
Y = (4, 3)

ValueError: ignored

e. np.dot(A.T, B)

In [ ]:
E=np.dot(X.T, Y)
print(E.shape)
#result: [[118 134 150][140 160 180]] ; the shape will be of 2 lines and 3 columns

(2, 3)

f. np.array([1,2,3])

In [ ]:
F=np.array([1,2,3])
print(F.shape)
#the dimension is representative for the given array:we have the number of lines, but the number of columns is absent

(3,)

g. A[:,1]

In [ ]:
G=X[:,1]
print(G.shape)
#result: [2 4 6 8] because the operation will pick every number of column 1 from every line; the shape will be of 4 lines, but the number of columns is absent

(4,)

h. A[:,1:2]

In [ ]:
H=X[:,1:2]
print(H.shape)
#Result: [[2][4][6][8]]; the shape will be of 4 lines and 1 column.

(4, 1)